### ISSUE TITLE
c99 & assembly errors

### ISSUE THREAD

**Issue by gmisail** [jsandler18/raspi-kernel#10]
First of all, I am getting errors around line 64 in gpu.c complaining about how declaring 'i' and 'j' in the for loop requires c99. Defining the variables outside the for loop does the trick, though.

Secondly, I am having issues compiling process_asm.s, due to a bad expression.

```
arm-none-eabi-gcc -mcpu=cortex-a7 -fpic -ffreestanding  -g -I../src/kernel -c ../src/kernel/process_asm.S -o objects/process_asm.o
../src/kernel/process_asm.S: Assembler messages:
../src/kernel/process_asm.S:17: Error: bad expression -- `ldr r0,=#(10000)'
```

I cloned your repo of section 9, corrected some of the paths in the Makefile, and compiled. 

If I play with the syntax of `=#(10000)`, sometimes I can get it to compile. However, I just get a wall of errors:

```
/Users/gmisail/Downloads/raspi-kernel-93d44a737728aa5fe366ad8ca62563e78987b023 2/build/../include/kernel/interrupts.h:17: multiple definition of `ENABLE_INTERRUPTS'
objects/interrupts.o:/Users/gmisail/Downloads/raspi-kernel-93d44a737728aa5fe366ad8ca62563e78987b023 2/build/../include/kernel/interrupts.h:17: first defined here
objects/process.o: In function `INTERRUPTS_ENABLED':
/Users/gmisail/Downloads/raspi-kernel-93d44a737728aa5fe366ad8ca62563e78987b023 2/build/../include/kernel/interrupts.h:17: multiple definition of `DISABLE_INTERRUPTS'
objects/interrupts.o:/Users/gmisail/Downloads/raspi-kernel-93d44a737728aa5fe366ad8ca62563e78987b023 2/build/../include/kernel/interrupts.h:17: first defined here
objects/timer.o: In function `INTERRUPTS_ENABLED':
/Users/gmisail/Downloads/raspi-kernel-93d44a737728aa5fe366ad8ca62563e78987b023 2/build/../include/kernel/interrupts.h:17: multiple definition of `INTERRUPTS_ENABLED'
objects/interrupts.o:/Users/gmisail/Downloads/raspi-kernel-93d44a737728aa5fe366ad8ca62563e78987b023 2/build/../include/kernel/interrupts.h:17: first defined here
objects/timer.o: In function `INTERRUPTS_ENABLED':
/Users/gmisail/Downloads/raspi-kernel-93d44a737728aa5fe366ad8ca62563e78987b023 2/build/../include/kernel/interrupts.h:17: multiple definition of `ENABLE_INTERRUPTS'
objects/interrupts.o:/Users/gmisail/Downloads/raspi-kernel-93d44a737728aa5fe366ad8ca62563e78987b023 2/build/../include/kernel/interrupts.h:17: first defined here
objects/timer.o: In function `INTERRUPTS_ENABLED':
/Users/gmisail/Downloads/raspi-kernel-93d44a737728aa5fe366ad8ca62563e78987b023 2/build/../include/kernel/interrupts.h:17: multiple definition of `DISABLE_INTERRUPTS'
objects/interrupts.o:/Users/gmisail/Downloads/raspi-kernel-93d44a737728aa5fe366ad8ca62563e78987b023 2/build/../include/kernel/interrupts.h:17: first defined here
collect2: error: ld returned 1 exit status
```

Thank you

**Comment by jsandler18** [comment]
For the second issue, the `=#(10000)` is expression syntax.  I think I meant to do `=#(1000*10)` but forgot.  `=10000` should probably work.

For the third issue,  `INTERRUPTS_ENABLED` is a function defined in `interrupts.h`, which is included in multiple places.  When I compile, I don't get this issue or the first issue.  This leads me to believe that the compiler I am using (gcc-arm-none-eabi-6-2017-q2-update) is smart enough to resolve the third issue and automatically compiles in c99.  Why yours does not do this, I cannot say.  The quick fix would be to move the definitions of the affected functions from the h file to the c file. I dont remember why i did it that way in the first place, but it was for a reason!

Good luck! let me know if you have any more questions!
