### ISSUE TITLE
process_asm.S issue with pushing sp

### ISSUE THREAD

**Issue by Dan12** [jsandler18/raspi-kernel#14]
In the file process_asm.S there might be an issue (I have been testing on a raspberry pi 2)

According to the arm specification, you should never push the sp ("reglist must not include the SP." from [here](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0802a/CIHJEHII.html)). I tried out your code on my pi and that line seemed to be crashing it. So I think line 11 of process_asm.S should be changed to `push {lr}` as we usually just want garbage there.

**Comment by jsandler18** [comment]
This has compiled and run for me in the past.  However my hardware was a raspi 1 model b, so my hardware might behave a bit differently. Feel free to make a pull request to change it.
