### ISSUE TITLE
qemu emulation shows black screen on macos

### ISSUE THREAD

**Issue by wcontayon** [jsandler18/raspi-kernel#15]
Hi 
Many thanks for this tutorial.
I stuck on the 2nd step on booting the myos.elf on qemu.
The emulation gives a black screen.
I'm using a macbook pro (macos mojave)

Thanks

**Comment by jsandler18** [comment]
Unfortunately, I do not know why this does not work for you.  If you can't get it to work, maybe try making a linux vm and trying to set it up in there

**Comment by vlabo** [comment]
I had the same problem and I found a solution.
to fix it you have to download [qemu source code](https://www.qemu.org/download/#source) and compile it with `--disable-gtk`
```
./configure --disable-gtk
make
```
When compiles it should be working fine.

I found the solution on qemu's [change log](https://wiki.qemu.org/ChangeLog/2.0)
`On MacOSX, the GTK and Cocoa UIs may not work properly if both are enabled; compile with --disable-gtk to work around this`
