### ISSUE TITLE
MakeFile not working

### ISSUE THREAD

**Issue by J-E-Mc** [jsandler18/raspi-kernel#16]
when i run the command "arm-none-eabi-gcc build/Makefile" after completing step 3 it gives me this error:

build/Makefile: file not recognized: file format not recognized
collect2.exe: error: ld returned 1 exit status

**Comment by jsandler18** [comment]
The command you want to run is just 'make'

**Comment by J-E-Mc** [comment]
sorry for taking so long to reply but make only says "nothing to be done for 'build'."

**Comment by jsandler18** [comment]
You should be in the building directory when you run make
