### ISSUE TITLE
problem with multi-core disable code on raspberry pi 3

### ISSUE THREAD

**Issue by descampsa** [jsandler18/raspi-kernel#4]
Your code to disable three of the four processors does not work properly for me.
I have tested with my own C code, that just switches a few gpios on and off on a raspberry pi 3, and with your current boot.S code, my code is not launched.

However, if i replace the line `cmp r1, #2` by `cmp r1, #0`, it works.
If i understand correctly, the effect of that change is that my code runs on the core 0, instead of the core 2. No idea why it makes a difference, maybe core 0 is special, somehow?
Is there any reason why you choose to use core 2?

**Comment by jsandler18** [comment]
Hm. Choosing 2 must have been a typo, as I certainly meant 0.

**Comment by Dan12** [comment]
I believe that on the actual hardware, it only ever starts up the first core and that you have to start up the other 3 cores manually, at least from what I have observed on my RPi 2.

**Comment by jsandler18** [comment]
This makes a lot more sense. The VM has tripped me up more than once.
