### ISSUE TITLE
The kfree function in mem.c is not setting the prev and next pointers correctly

### ISSUE THREAD

**Issue by thetorine** [jsandler18/raspi-kernel#6]
Combining the heap segments to the left does not update the `seg->next->prev` pointer to point to the previous heap segment.

Similar problem when combining on the right where the `seg->next->next->prev` pointer is not updated to the current heap segment. 

Freeing pointers in the same order they were allocated is causing the `segment_size` field to become larger than the amount in the initial heap segment. I haven't tested any other scenarios but correctly setting the pointers as outlined above along with null checks solved the issue.

**Comment by jsandler18** [comment]
Well that is embarrassing.  Thanks for the heads up.  It should be fixed now.
