### ISSUE TITLE
Undefined Reference to all assembly defined functions

### ISSUE THREAD

**Issue by TheGrimSilence** [jsandler18/raspi-kernel#7]
Compiling the OS code in the repository gives me u definitened reference errors to `move_exception_vector` `try_lock` and `switch_to_thread`. Am I doing something wrong? Or is there an issue in the makefile?

**Comment by jsandler18** [comment]
The makefile is fine. Are you using the right version of gcc?

**Comment by TheGrimSilence** [comment]
I have the latest from the ARM Developer site being 7-2017-q4-major

**Comment by jsandler18** [comment]
Hm.  I am not sure.  Can you post a screenshot or a textdump of the error message?

**Comment by TheGrimSilence** [comment]
![screenshot_9](https://user-images.githubusercontent.com/11479772/38227702-904d3086-36cd-11e8-8a35-9b1db2805af6.png)

**Comment by TheGrimSilence** [comment]
I have found some typos that have fixed a few things.
```diff
- ENTRY(_start)
+ ENTRY(__start)
```
```diff
src/kernel/boot.S
- .globl _start
+ .global _start
```

**Comment by jsandler18** [comment]
Have you modified anything? Those references are undefined because, from the looks of it, your assembly files are not even trying to be compiled
