### ISSUE TITLE
Is it just me?

### ISSUE THREAD

**Issue by timkoers** [jsandler18/raspi-kernel#9]
When I run the latest commit in the qemu emulator and connect to the VNC server with vncviewer, the screen stays black and nothing that I type in the terminal get's echo'ed back. I can't see any boot text either. 
Where do I start with debugging?

**Comment by jsandler18** [comment]
The latest commit uses the framebuffer to display all text which is not implemented in any emulator that I am aware of. If you have actual hardware, it should work
